Mila/multi db
firebase/firebase-cpp-sdk pull request #1321
Opened 2023-05-12 17:14 UTC by milaGGL

### Description
> Provide details of the change, and generalize the change in the PR title above.

[replace this line]: # (Describe your changes in detail.)
***
### Testing
> Describe how you've tested these changes. Link any manually triggered `Integration tests` or `CPP binary SDK Packaging` Github Action workflows, if applicable.

[replace this line]: # (Describe your testing in detail.)
***

### Type of Change
Place an `x` the applicable box:
- [ ] Bug fix. Add the issue # below if applicable.
- [ ] New feature. A non-breaking change which adds functionality.
- [ ] Other, such as a build process or documentation change.
***

#### Notes
- Bug fixes and feature changes require an update to the `Release Notes` section of `release_build_files/readme.md`.
- Read the contribution guidelines [CONTRIBUTING.md](https://github.com/firebase/firebase-cpp-sdk/blob/main/CONTRIBUTING.md).
- Changes to the public API require an internal API review. If you'd like to help us make Firebase APIs better, please propose your change in a feature request so that we can discuss it together.

2023-05-15 15:18 UTC, tom-andersen requested changes

2023-05-16 20:20 UTC, tom-andersen reviewed
LGTM

2023-05-16 20:20 UTC, tom-andersen commented on firestore/src/common/firestore.cc
>  Firestore* Firestore::CreateFirestore(App* app,
We can do this in separate PR.

2023-05-16 20:20 UTC, tom-andersen commented on firestore/src/include/firebase/firestore.h
>    static Firestore* CreateFirestore(::firebase::App* app,
We can do this in separate PR.

2023-05-18 15:19 UTC, wu-hui reviewed
Close to LGTM!

I do want to see less usage of `const char*` though, we should try to avoid raw pointers, especially when database id is not expensive to copy around.

2023-05-18 15:19 UTC, wu-hui commented on firestore/src/main/firestore_main.h
> +  const std::string& database_name() const { return database_name_; }
database_name is overloaded here, there is a database_id already, which is a combination of project id and database id/name.

I don't think having a separate database_name_ field is the way to go, we can reuse the existing database_id() from firestore_core_.

2023-05-18 15:19 UTC, wu-hui commented on firestore/src/main/firestore_main.h
> +  const std::string& database_name() const { return database_name_; }
You can still keep the database_name() method because it looks easier for Android.

2023-05-18 16:56 UTC, milaGGL commented on firestore/src/include/firebase/firestore.h
> +                                const char* db_name,
In the original API proposal , it was `const std::string&`, and later requested to be changed to `const char*`. I am not sure why.

2023-05-18 17:28 UTC, milaGGL commented on firestore/integration_test_internal/src/firestore_test.cc
> +  if (!IsUsingFirestoreEmulator()) {
`integration_test_internal/src/firebase_test_framework.h` is a generated file. Lemme check where do we set up the macros.

2023-05-18 20:44 UTC, milaGGL commented on firestore/src/common/firestore.cc
> +  FirestoreCache()->emplace(key, firestore);
`FirestoreCache()->emplace(MakeKey(firestore->app(), firestore->internal_->database_name()), firestore);` looks too long to read.

2023-05-18 21:02 UTC, milaGGL commented on firestore/integration_test_internal/src/firestore_test.cc
> +  DeleteFirestore(db1);
Yes, I added a new comprehensive integration test to cover the 2 scenario u mentioned.

2023-05-18 21:04 UTC, milaGGL commented on firestore/integration_test_internal/src/util/locate_emulator.cc
> +bool IsUsingFirestoreEmulator() {
This new function is removed since a new macro `RUN_TEST_ONLY_AGAINST_FIRESTORE_EMULATOR` is added instead.

2023-05-19 16:56 UTC, milaGGL commented on firestore/integration_test_internal/src/firestore_test.cc
> +TEST_F(FirestoreTest, ComprehensiveTestOnMultiDbCreationAndTermination) {
New test added.

2023-05-19 18:15 UTC, wu-hui commented on firestore/src/include/firebase/firestore.h
> +                                const char* db_name,
OK, at least we should find out why. I suppose there is a reason they asked for this.

2023-05-19 18:20 UTC, wu-hui approved these changes
LGTM, good work!

2023-05-19 18:36 UTC, tom-andersen approved these changes

2023-05-19 18:38 UTC, merged