Auth deprecated methods removal
firebase/firebase-cpp-sdk pull request #1575
Opened 2024-04-25 22:46 UTC by jonsimantov

### Description
> Provide details of the change, and generalize the change in the PR title above.

Remove methods that were deprecated in the 11.0.0 release last year.
***
### Testing
> Describe how you've tested these changes. Link any manually triggered `Integration tests` or `CPP binary SDK Packaging` Github Action workflows, if applicable.

[replace this line]: # (Describe your testing in detail.)
***

### Type of Change
Place an `x` the applicable box:
- [ ] Bug fix. Add the issue # below if applicable.
- [ ] New feature. A non-breaking change which adds functionality.
- [ ] Other, such as a build process or documentation change.
***

#### Notes
- Bug fixes and feature changes require an update to the `Release Notes` section of `release_build_files/readme.md`.
- Read the contribution guidelines [CONTRIBUTING.md](https://github.com/firebase/firebase-cpp-sdk/blob/main/CONTRIBUTING.md).
- Changes to the public API require an internal API review. If you'd like to help us make Firebase APIs better, please propose your change in a feature request so that we can discuss it together.

2024-04-30 20:53 UTC, a-maurice requested changes
Going to need to update the Auth unit tests (the stuff under auth/tests) too

2024-04-30 21:28 UTC, a-maurice reviewed
Another sanity check to try, run the reference doc generation, and make sure that looks good.

2024-04-30 21:28 UTC, a-maurice commented on auth/src/include/firebase/auth.h
>  struct AuthResultCompletionHandle;
I think you delete AuthCompletionHandle in this change, so remove it here too

2024-04-30 21:28 UTC, a-maurice commented on auth/src/desktop/auth_providers/federated_auth_provider.cc
>  // Helper function which uses the AuthCompletionHandle to plumb an
AuthResultCompletionHandle

2024-05-01 00:48 UTC, a-maurice approved these changes

2024-05-01 18:15 UTC, jonsimantov commented
> Another sanity check to try, run the reference doc generation, and make sure that looks good.

Makes sense - running packaging workflow to generate docs from.

2024-05-03 00:15 UTC, jonsimantov commented
> Another sanity check to try, run the reference doc generation, and make sure that looks good.

Confirmed that docs generation looks good, merging this.

2024-05-03 00:40 UTC, merged