Removing google play requirement.
firebase/firebase-cpp-sdk pull request #361
Opened 2021-04-09 19:47 UTC by vimanyu

Firebase Android SDKs for Auth, Database, Storage, Functions do not require Google Play Services anymore.
https://firebase.google.com/docs/android/android-play-services

Removing checks for Google Play services for these products from the C++ SDK. 
Tested by running integration tests on, 
- devices with Google play services (https://github.com/firebase/firebase-cpp-sdk/actions/runs/730345555)
- devices without Google Play services (tested on Kindle)
- android emulator images with and without google play services. 

Addresses https://github.com/firebase/quickstart-unity/issues/975

2021-04-09 19:47 UTC, vimanyu commented
Not sure if we still need the App callback but I left it in there for now. Let me know if that can be safely removed too.

2021-04-09 20:15 UTC, a-maurice submitted a review, later dismissed

2021-04-12 18:00 UTC, jonsimantov commented
> Not sure if we still need the App callback but I left it in there for now. Let me know if that can be safely removed too.

What do you mean by "App callback"?

2021-04-12 18:00 UTC, jonsimantov requested changes
Could you add an update to the readme file?

2021-04-12 19:10 UTC, jonsimantov commented on release_build_files/readme.md
> +    -   General: Removed checks for Google Play Services in C++ for Auth, Database,
General (Android):

2021-04-12 19:13 UTC, jonsimantov commented on release_build_files/readme.md
> +    -   General: Removed checks for Google Play Services in C++ for Auth, Database,
Also, it should be spelled "Google Play services" (with a lower-case "s")

2021-04-12 19:20 UTC, jonsimantov approved these changes

2021-04-12 19:20 UTC, jonsimantov commented
> > Not sure if we still need the App callback but I left it in there for now. Let me know if that can be safely removed too.
> 
> What do you mean by "App callback"?

I figured out what you meant - those are needed for the Unity SDK to initialize the various C++ modules, I believe, and should be kept in place for now.

2021-04-12 19:22 UTC, merged