Made parameters in QueryParams optional.
firebase/firebase-cpp-sdk pull request #391
Opened 2021-04-23 08:13 UTC by alexames

QueryParams previous used null variants and empty strings to indicate
that a field should not be used as a filter. This creates a problem when
you want to filter by something that has a null value or an empty
string. To fix this std::string and Variant have been replaced with
Optional<std::string> and Optional<Variant> so that "filter on null" is
distinct from "there is no filter".

2021-04-26 15:11 UTC, DellaBitta requested changes

2021-04-26 22:16 UTC, alexames commented on database/src/desktop/query_params_comparator.h
> +  int Compare(const std::pair<V1, V1>& a, const std::pair<V2, V2>& b) const {
I didn't remove the key_ and value_ prefixes. There are two versions of this function: one that takes a pair and one that takes individual key and values as separate arguments. I think in my refactoring the two functions reversed their order, but they're both still there.

2021-04-29 10:44 UTC, alexames commented on database/src/desktop/query_params_comparator.cc
> +  assert(key_a->is_string() || key_a->is_int64());
Changes to this function ended up not being necessary at all.

2021-04-29 10:44 UTC, alexames commented on database/src/desktop/query_params_comparator.h
> +  int Compare(const std::pair<V1, V1>& a, const std::pair<V2, V2>& b) const {
Same here, I ended up reverting this part of the change.

2021-04-29 13:28 UTC, DellaBitta approved these changes

2021-05-03 17:22 UTC, jonsimantov approved these changes

2021-05-04 07:23 UTC, merged