Fix Firestore transaction_extra_test.cc on iOS and re-enable the tests
firebase/firebase-cpp-sdk pull request #426
Opened 2021-05-13 20:33 UTC by dconeybe

The tests were hanging indefinitely and therefore were disabled. The root cause was the call to `Await()` in the transaction callback thread, which eventually called `ProcessEvents()` in `ios_app_framework.mm`. The `ProcessEvents()` function was coded in such a way that it would only handle being called from the main thread, and, therefore, when called from a non-main thread, caused undefined behavior (in this case, a hang). I re-wrote the concurrency logic in `ios_app_framework.mm` and that fixed the tests.

2021-06-04 23:59 UTC, var-const requested changes
Overall looking good! Just some nits.

2021-06-04 23:59 UTC, var-const commented on testing/sample_framework/src/ios/ios_app_framework.mm
> +static int g_exit_status = -1;
Nit: it seems a little inconsistent that `status` is used in two closely related variables but has slightly different meanings. How about `s/RunningStatus/RunningState/`?

2021-06-04 23:59 UTC, var-const commented on testing/sample_framework/src/ios/ios_app_framework.mm
> +    auto common_main_result = common_main(1, argv);
Nit: consider spelling out the type here.

2021-06-04 23:59 UTC, var-const commented on testing/sample_framework/src/ios/ios_app_framework.mm
> +    if ([currentDate compare:endDate] == NSOrderedAscending) {
Question: what is the reason to check this manually? Is there any advantage to calling `wait` unconditionally and letting its implementation figure out if enough time has passed?

2021-06-07 17:51 UTC, var-const approved these changes
Consider expanding the rationale in the PR description -- some of the details you shared over chat seem very useful in general. Perhaps something like (feel free to change as necessary):
```
Previously, this code would only lock `g_shutdown_signal` once, before calling `common_main`. Let's say the thread that does this is `T1`. `ProcessEvents` requires the calling thread to possess the lock, which is only true if it is called from `T1`; if `ProcessEvents` is called from any other thread, it will hang (because it can never acquire the lock).
```

2021-06-07 18:03 UTC, dconeybe commented
> Consider expanding the rationale in the PR description

Done. I just copied your suggestion verbatim :)

2021-06-07 18:05 UTC, merged