Feature/tvos support
firebase/firebase-cpp-sdk pull request #443
Opened 2021-06-02 19:25 UTC by vimanyu

This is specifically for building tvOS libraries for both device and simulator. For testing the built libraries, there will be another PR that ensures all integration tests are working.

- single toolchain file that could possibly be used in the future for iOS as well as mac builds. Currently being used only for tvOS.
- Disabled AdMob and Dynamic Links as they are not supported on tvOS.
- Disabled some functionality from auth (PhoneAuthProvider) that doesn't exist on tvOS.
- Disabled some functionality in FCM (since some of the frameworks we are using do not exist on tvOS). FCM might require more work for full functionality on tvOS but it doesn't block the builds.

2021-06-02 20:08 UTC, DellaBitta requested changes

2021-06-02 20:08 UTC, DellaBitta commented on build_scripts/tvos/install_prereqs.sh
> +    echo "Unsupported platform, iOS can only be build on a MacOS machine."
tvOS, not iOS

2021-06-02 20:08 UTC, DellaBitta commented on build_scripts/tvos/package.sh
> +
This should have some sort of header, like our other package scripts.

2021-06-02 20:08 UTC, DellaBitta commented on cmake/toolchains/apple.toolchain.cmake
> +# This file is part of the ios-cmake project. It was retrieved from
I think you should add the Google copyright to the top of this file, too, and also create a entry for this in the `release_build_files/NOTICES` file.

2021-06-03 01:09 UTC, vimanyu commented on app/src/app_common.cc
>  const char* kOperatingSystem = "ios";
Great catch and thank you for spotting this!

2021-06-03 19:28 UTC, vimanyu commented
Thanks for the comments! All have been addressed!

2021-06-03 20:05 UTC, DellaBitta requested changes

2021-06-03 20:05 UTC, DellaBitta commented on build_scripts/tvos/package.sh
> +    echo "Usage: $0 <built tvOS SDK path> <path to put packaged files into>"
call usage() here intead.

2021-06-03 20:05 UTC, DellaBitta commented on build_scripts/tvos/package.sh
> +    echo "Built tvOS SDK not found at path '${builtpath}'."
Call usage() here, too.

2021-06-03 20:11 UTC, vimanyu commented on build_scripts/tvos/package.sh
> +    echo "Usage: $0 <built tvOS SDK path> <path to put packaged files into>"
oops! Missed it! Done!

2021-06-03 20:36 UTC, DellaBitta approved these changes

2021-06-03 20:46 UTC, merged