Automatically update iOS and Android dependencies.
firebase/firebase-cpp-sdk pull request #629
Opened 2021-09-08 18:09 UTC by jonsimantov

2021-09-08 22:03 UTC, jonsimantov commented
Sample PR created by this workflow: https://github.com/firebase/firebase-cpp-sdk/pull/635

2021-09-09 02:12 UTC, jonsimantov commented
This is now ready for review!

Sample run: https://github.com/firebase/firebase-cpp-sdk/actions/runs/1215602717
Sample PR created by this workflow: https://github.com/firebase/firebase-cpp-sdk/pull/645

2021-09-09 13:06 UTC, DellaBitta requested changes
Double check admob's dependency version.

2021-09-10 16:57 UTC, jonsimantov commented on Android/firebase_dependencies.gradle
> +  'admob' : ['com.google.firebase:firebase-ads:19.4.0',
No, was being used for testing - reverting.

2021-09-10 16:58 UTC, jonsimantov commented on .github/workflows/update-dependencies.yml
> +              echo "CHOSEN_DEPS=" >> $GITHUB_ENV
How about "Android and iOS"? :)

2021-09-10 17:00 UTC, jonsimantov commented on .github/workflows/update-dependencies.yml
> +      - name: Create new branch
Fixed.

2021-09-10 17:00 UTC, jonsimantov commented on .github/workflows/update-dependencies.yml
> +          fi
Sure, why not. Added.

2021-09-10 17:07 UTC, jonsimantov commented on scripts/gha/create_pull_request.py
> +FLAGS = flags.FLAGS
Mostly it's historical, I think - scripts originally from our internal repo generally use absl flags, scripts that were written as open-source first use either python flags, or, if they are based on an existing script that uses absl flags, absl flags.

Agree that we should at some point standardize - I'd actually love not to use absl-py flags at all at some point in the future, as that would be one less dependency.

2021-09-10 17:11 UTC, jonsimantov commented
New sample PR: https://github.com/firebase/firebase-cpp-sdk/pull/646

2021-09-10 17:28 UTC, jonsimantov commented
> Double check admob's dependency version.

It's just using the AdMob version set by default in update_android_ios_dependencies.py - when this needs to change, that script should be modified.

2021-09-10 17:28 UTC, jonsimantov commented on .github/workflows/update-dependencies.yml
> +              echo "CHOSEN_DEPS=" >> $GITHUB_ENV
Actually I think "mobile" is nicer, let's see how that looks.

2021-09-10 19:50 UTC, DellaBitta approved these changes

2021-09-10 20:29 UTC, merged