Properly convert milliseconds to seconds
firebase/firebase-cpp-sdk pull request #767
Opened 2021-11-30 12:33 UTC by pawelsnk

Currently, a value expressed in milliseconds is directly assigned to a variable
which is supposed to store seconds and it's later converted to mills again.
Thus, convert properly upon assignment

### Description
> Provide details of the change, and generalize the change in the PR title above.

Currently, a value expressed in milliseconds is directly assigned to a variable
which is supposed to store seconds and it's later converted to mills again.
Thus, convert properly upon assignment

***
### Testing
> Describe how you've tested these changes. Link any manually triggered `Integration tests` or `CPP binary SDK Packaging` Github Action workflows, if applicable.

Setting different timeouts via RemoteConfig::SetConfigSettings(), calling RemoteConfig::FetchAndActivate() and verifying if an expected update was indeed fetched or cached config was used.
***

### Type of Change
Place an `x` the applicable box:
- [x] Bug fix. Add the issue # below if applicable.
- [ ] New feature. A non-breaking change which adds functionality.
- [ ] Other, such as a build process or documentation change.
***

#### Notes
- Bug fixes and feature changes require an update to the `Release Notes` section of `release_build_files/readme.md`.
- Read the contribution guidelines [CONTRIBUTING.md](https://github.com/firebase/firebase-cpp-sdk/blob/main/CONTRIBUTING.md).
- Changes to the public API require an internal API review. If you'd like to help us make Firebase APIs better, please propose your change in a feature request so that we can discuss it together.

2021-11-30 12:39 UTC, pawelsnk commented
I've just signed CLA. Please rerun

2021-11-30 19:03 UTC, cynthiajoan approved these changes

2021-11-30 19:06 UTC, jonsimantov commented
Thanks for the bugfix! Could you please add a release note to `release_build_files/readme.md`, under "Next Release"?

2021-12-01 07:53 UTC, pawelsnk commented
> Thanks for the bugfix! Could you please add a release note to `release_build_files/readme.md`, under "Next Release"?

Done. Please squash all the commits when merging.

BTW: There has been some test failures but that looks unrelated.

2021-12-01 19:11 UTC, jonsimantov requested changes

2021-12-01 19:11 UTC, jonsimantov commented on release_build_files/readme.md
> +    - Remote config (Desktop): Fixed cache expiration time value used by
Can you fix the indents to match the above lines? (4 spaces before the hyphen then 3 spaces after the hyphen; on the following lines, 8 space indent, no tabs). Also could you fix the capitalization to "Remote Config"?

Thanks!

2021-12-02 07:41 UTC, jonsimantov approved these changes

2021-12-02 07:42 UTC, merged

2021-12-02 07:44 UTC, jonsimantov commented
> > Thanks for the bugfix! Could you please add a release note to `release_build_files/readme.md`, under "Next Release"?
> 
> Done. Please squash all the commits when merging.
> 
> BTW: There have been some test failures but that looks unrelated.

Thanks for the readme fixes as well! It's been squashed and merged. The test failures were indeed unrelated.

Your fix made it in just in time for the next C++ release, and will also be included in the next Unity release.

2021-12-02 07:47 UTC, pawelsnk commented
> > > Thanks for the bugfix! Could you please add a release note to `release_build_files/readme.md`, under "Next Release"?
> > 
> > 
> > Done. Please squash all the commits when merging.
> > BTW: There have been some test failures but that looks unrelated.
> 
> Thanks for the readme fixes as well! It's been squashed and merged. The test failures were indeed unrelated.
> 
> Your fix made it in just in time for the next C++ release, and will also be included in the next Unity release.

🎉 Thanks!