Feature/uitest workflow
firebase/firebase-cpp-sdk pull request #916
Opened 2022-04-28 18:41 UTC by sunmou99

### Description
> Provide details of the change, and generalize the change in the PR title above.

[replace this line]: # (Describe your changes in detail.)
***
### Testing
> Describe how you've tested these changes. Link any manually triggered `Integration tests` or `CPP binary SDK Packaging` Github Action workflows, if applicable.

[replace this line]: # (Describe your testing in detail.)
***

### Type of Change
Place an `x` the applicable box:
- [ ] Bug fix. Add the issue # below if applicable.
- [ ] New feature. A non-breaking change which adds functionality.
- [ ] Other, such as a build process or documentation change.
***

#### Notes
- Bug fixes and feature changes require an update to the `Release Notes` section of `release_build_files/readme.md`.
- Read the contribution guidelines [CONTRIBUTING.md](https://github.com/firebase/firebase-cpp-sdk/blob/main/CONTRIBUTING.md).
- Changes to the public API require an internal API review. If you'd like to help us make Firebase APIs better, please propose your change in a feature request so that we can discuss it together.

2022-05-03 15:27 UTC, DellaBitta commented
Why is the TestAdInspector test disabled / commented out?

2022-05-03 17:13 UTC, sunmou99 commented
> Why is the TestAdInspector test disabled / commented out?

We agreed not to include TestAdInspector in to our [UI Tests](https://docs.google.com/document/d/1a01c5W4U26tataczYw-sv5k_YsfVy4DBhuj_CdhEF8M/edit?resourcekey=0-qAIEiUCh4uHJoxCQZjgZnA#heading=h.cg1leil5anlr). 
Do you want to added it back?

2022-05-04 00:05 UTC, DellaBitta commented
Yes, it should still be part of manual testing.

2022-05-05 15:35 UTC, DellaBitta requested changes

2022-05-05 19:33 UTC, sunmou99 commented
> Yes, it should still be part of manual testing.

Added back:)

2022-05-05 20:18 UTC, DellaBitta commented on gma/integration_test/src/integration_test.cc
> +  // EXPECT_EQ(content_listener.num_ad_clicked(), 1);
Is there a way to conditionally check if this is being manually tested (or rather, not automatically tested) and add the check in those scenarios?

Failing that a big noticeable log of "Received %d num_ad_clicked events".

2022-05-05 20:36 UTC, sunmou99 commented on gma/integration_test/src/integration_test.cc
> +  // EXPECT_EQ(content_listener.num_ad_clicked(), 1);
It's possible but the code may look weird. Let me add some comment as well.

2022-05-05 22:55 UTC, DellaBitta approved these changes

2022-05-06 02:20 UTC, merged