blastdoor configuration for re2
firebase/firebase-cpp-sdk pull request #981
Opened 2022-06-02 03:07 UTC by dconeybe

The PR https://github.com/firebase/firebase-ios-sdk/pull/9488 in the firebase-ios-sdk added a dependency on a new third-party library, "re2". This was picked up by the firebase-cpp-sdk in https://github.com/firebase/firebase-cpp-sdk/pull/977.

All of the CI builds and tests worked fine; however, the "blastdoor" post-processing step renamed the `re2` namespace that caused linking error when linking against the packaged SDK (e.g. https://github.com/firebase/firebase-cpp-sdk/runs/6701070693).

This PR fixes the linking error by configuring blastdoor to properly handle re2. This was 100% based on the same thing for the snappy dependency in https://github.com/firebase/firebase-cpp-sdk/pull/885.

2022-06-02 03:13 UTC, dconeybe commented
CPP binary SDK packaging workflow started: https://github.com/firebase/firebase-cpp-sdk/actions/runs/2425793137

2022-06-02 12:01 UTC, dconeybe commented
Integration test triggered against the packaging workflow: https://github.com/firebase/firebase-cpp-sdk/actions/runs/2428059862

2022-06-02 12:06 UTC, dconeybe commented
Trying the packaging workflow again: https://github.com/firebase/firebase-cpp-sdk/actions/runs/2428095690

2022-06-02 17:17 UTC, dconeybe commented
I've kicked off the integration tests to test the build artifacts of the packaging workflow 2428095690 mentioned in the previous comment: https://github.com/firebase/firebase-cpp-sdk/actions/runs/2429785219

2022-06-02 18:34 UTC, cynthiajoan approved these changes

2022-06-02 19:53 UTC, jonsimantov approved these changes
Looks good in the packaging run log. Hopefully the integration tests work.

2022-06-03 03:41 UTC, jonsimantov requested changes

2022-06-03 03:41 UTC, jonsimantov commented on release_build_files/readme.md
> +    - Firestore (Windows): dbghelp and bcrypt need to be linked against.
Firestore (Desktop): On Windows, you must now link against bcrypt and dbghelp system libraries.

2022-06-03 17:30 UTC, jonsimantov approved these changes

2022-06-03 18:28 UTC, merged